name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Runs daily
  workflow_dispatch:              # Allows manual trigger
  push: {branches: ["master", "main"]}  # Optional: run on push to main/master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
